spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prompt_share
    username: prompt
    password: prompt4242
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:prompt;mode=mysql
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always